// Shared library for the kit-owned cross-project memory tier.
//
// The tier holds learned FACTS that span projects: machine/environment facts
// (this box drops VPN secrets on netplan reload) and platform facts (this
// product's deployment convention). Project-specific facts stay in Claude
// Code's native per-project auto-memory, which this kit does not touch, and
// recurring working preferences are doctrine that graduates to the global
// CLAUDE.md through reconcile-claude-md rather than accumulating here.
//
// The store roots at ~/.claude-kit-memory/, deliberately outside both
// ~/.claude and ~/.claude-work. Those directories hold .credentials.json,
// settings.json, and history.jsonl, so a memory tier nested inside one can
// only be synced behind an allowlist that is the sole barrier between
// "sync memories" and "publish credentials". A tier the kit owns picks a
// clean root instead and needs no such barrier. ~/.claude-kaizen/ is the
// established precedent for a kit-owned home-rooted directory.
//
// ---------------------------------------------------------------------------
// RECORD SCHEMA. One file per fact, <name>.md under the store root.
//
//   ---
//   name: kebab-case-slug          authored; must equal the filename stem
//   description: <one line>        authored; LOAD-BEARING, see below
//   metadata:
//     kind: machine | platform     authored; machine = true of a box or
//                                  account, platform = true of a body of work
//                                  spanning repos
//     machine: <label>             authored, optional; set only when the fact
//                                  is true of one box, so another machine can
//                                  see it labelled as foreign
//     created: YYYY-MM-DD          generated on first write
//     modified: <ISO 8601>         generated on every write
//     applied: [YYYY-MM-DD, ...]   generated by the apply stamp; distinct days
//                                  only. Drives advisory decay ranking and
//                                  CANNOT be reconstructed after the fact
//     origin: <free label>         authored, optional; where the fact was
//                                  learned
//   ---
//   <body: the detail, evidence, and any counter-case>
//
// `description` is load-bearing because it GENERATES the line this tier emits
// into session context. It must carry the correction, not a topic label:
// "netplan drops NM VPN secrets, use a native keyfile, not nmcli modify"
// rather than "dev box VPN gotcha". A topic label intercepts nothing.
//
// Generating that line rather than maintaining a second copy of it is the
// central decision of this tier. In the native store, index currency is a
// byproduct of CREATING a record (15 of 15 sessions) and never an act of
// REVISING one (0 of 8), so a hand-maintained line drifts from its record as
// a matter of course. One copy cannot diverge from itself.
//
// Records are never written with the Write tool. The CLI is the only writer,
// so that lock discipline, field validation, and the generated stamps all
// hold; a hand-edited record is tolerated on read but is not the write path.
//
// Change detection uses CONTENT HASHES, not mtime. Applying a stamp rewrites
// the record file, so mtime advances on records whose text nobody revised,
// and a mtime-based "body revised" signal would fire on every stamped record.
// Hashing description and body separately answers the actual question: did
// the body change while the description that advertises it did not?
// ---------------------------------------------------------------------------
//
// Node core modules only, CommonJS, zero dependencies. Every exported
// function that touches the filesystem or parses data is wrapped so it never
// throws; a filesystem hiccup or a malformed record degrades to a null/empty/
// typed-failure result instead of trapping the caller. A hook must never
// crash a session over a memory read.

'use strict';

const crypto = require('crypto');
const fs = require('fs');
const os = require('os');
const path = require('path');

// Bytes read when only the frontmatter is wanted. A record whose frontmatter
// runs past this is NOT silently dropped: the reader retries at the full cap
// rather than reporting an unterminated block, because a record that reads
// fine by name while being invisible to the index is the worst failure this
// tier can have.
const FRONTMATTER_READ_CAP = 4096;

// Bytes read for a whole record.
const RECORD_READ_CAP = 256 * 1024;

// A record name is the file's stem and rides into the model's context on the
// emitted line, so it is constrained at both ends: kebab-case only (no path
// separators, no traversal, no leading dot) and bounded.
const NAME_PATTERN = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;
const NAME_MAX = 80;

// Bounds the description so a record cannot push its own frontmatter past the
// prefix read, and keeps the emitted line to one legible line. The native
// store's longest real index line is 345 chars.
const DESCRIPTION_MAX = 400;

// The two kinds of fact this tier holds. Deliberately NOT native's
// user/feedback/project/reference set: `project` is meaningless in a
// cross-project tier and `feedback` graduates to doctrine instead of living
// here, so reusing that key name under different values would be a trap with
// both stores open.
const KINDS = ['machine', 'platform'];

const DATE_PATTERN = /^\d{4}-\d{2}-\d{2}$/;

// Metadata fields that are lists whatever their written form. Bracket syntax
// drives the general parse so a future list field behaves without being
// listed here, but these are normalized to an array regardless: a
// hand-written `applied: 2026-08-01` must not read as a scalar and then be
// written back as an empty list, which would destroy history the schema
// calls unreconstructable.
const LIST_FIELDS = ['applied'];

// Store root. The env override exists for tests and for an operator who keeps
// their home directory elsewhere. It is resolved to an absolute path: a
// relative value would make the store cwd-dependent, which is the one
// property this tier exists to avoid.
function storeRoot() {
    const override = process.env.CLAUDE_KIT_MEMORY_DIR;
    if (override && override.trim()) return path.resolve(override.trim());
    return path.join(os.homedir(), '.claude-kit-memory');
}

// Path to a record. Validates rather than trusting its caller, because this
// is exported and a name that reached it from parsed frontmatter rather than
// from a directory listing would otherwise traverse. Returns null on a bad
// name.
function recordPath(name) {
    if (!validateName(name).ok) return null;
    return path.join(storeRoot(), name + '.md');
}

function validateName(name) {
    if (typeof name !== 'string' || !name) return { ok: false, reason: 'name is required' };
    if (name.length > NAME_MAX) return { ok: false, reason: 'name exceeds ' + NAME_MAX + ' characters' };
    if (!NAME_PATTERN.test(name)) {
        return { ok: false, reason: 'name must be kebab-case (lowercase letters, digits, single dashes)' };
    }
    return { ok: true };
}

// Every string this module writes into a record passes here. A newline would
// break the frontmatter block and let a record forge a field or a block
// terminator, and `description` is what generates emitted context, so a
// forged one reaches the model as an assertion to act on. Applied at every
// door, not just the obvious one: name, description, and every metadata
// value including array elements.
function validateFieldText(value, label) {
    if (typeof value !== 'string') return { ok: false, reason: label + ' must be a string' };
    if (/[\x00-\x1F\x7F]/.test(value)) {
        return { ok: false, reason: label + ' must be a single line with no control characters' };
    }
    return { ok: true };
}

// Reduce a string to bounded printable ASCII for a channel the model reads.
// Substitutes a space rather than deleting, unlike session-start.js's strip:
// deletion splices adjacent tokens into one word, substitution does not.
function sanitize(value, cap) {
    if (typeof value !== 'string') return '';
    const stripped = value.replace(/[^\x20-\x7E]/g, ' ').replace(/\s+/g, ' ').trim();
    return cap && stripped.length > cap ? stripped.slice(0, cap) : stripped;
}

// Stable content hash, used by the index sidecar to tell a revised body from
// a revised description. Short because it is stored per record and only ever
// compared for equality.
function hashOf(value) {
    return crypto.createHash('sha256').update(String(value == null ? '' : value), 'utf8').digest('hex').slice(0, 16);
}

// Read a bounded prefix of a file, plus its mtime from the same descriptor.
// Opens with O_NONBLOCK and confirms regular-file-ness on the descriptor
// itself: a stat-then-open pair leaves a TOCTOU window, and openSync on a
// FIFO blocks until a writer appears, which would hang a hook that promises
// never to block. Taking mtime from the same fd keeps it describing the bytes
// actually read. Returns null on any failure.
function readCapped(file, cap) {
    let fd;
    try {
        fd = fs.openSync(file, fs.constants.O_RDONLY | fs.constants.O_NONBLOCK);
    } catch {
        return null;
    }
    try {
        const stat = fs.fstatSync(fd);
        if (!stat.isFile()) return null;
        const buf = Buffer.alloc(cap);
        const bytes = fs.readSync(fd, buf, 0, cap, 0);
        let text = buf.toString('utf8', 0, bytes);
        if (text.charCodeAt(0) === 0xFEFF) text = text.slice(1);
        return { text, mtimeMs: stat.mtimeMs, truncated: stat.size > bytes };
    } catch {
        return null;
    } finally {
        try { fs.closeSync(fd); } catch { /* already closed or invalid */ }
    }
}

// Strip one layer of YAML quoting. Native auto-memory quotes some
// descriptions and this tier is hand-editable, so the reader tolerates the
// form. Guarded: a value that merely starts and ends with a quote character
// ("search_code" is X, per "the docs") is content, not a quoted string, and
// unquoting it would corrupt the field that generates the emitted line.
function unquote(value) {
    const v = value.trim();
    if (v.length < 2) return v;
    const q = v[0];
    if ((q !== '"' && q !== "'") || !v.endsWith(q)) return v;
    if (v.slice(1, -1).includes(q)) return v;
    return v.slice(1, -1);
}

// Parse a YAML scalar or inline list. Bracket syntax drives the decision, not
// the key name, so a future list-valued field behaves and a hand-written
// bracket-less `applied: 2026-08-01` becomes a one-element list instead of
// being silently emptied on the next write.
function parseScalarOrList(raw) {
    const v = raw.trim();
    if (v.startsWith('[') && v.endsWith(']')) {
        const inner = v.slice(1, -1).trim();
        if (!inner) return [];
        return inner.split(',').map(s => unquote(s)).filter(Boolean);
    }
    return unquote(v);
}

// Parse a record's text into { ok, record } or { ok:false, reason }.
//
// A deliberately narrow reader for the format this kit emits, not a YAML
// parser: a frontmatter block delimited by --- lines, top-level `key: value`,
// and one nested `metadata:` map. Anything outside that shape is reported
// rather than dropped, because a silent drop is how a stamp that cannot be
// reconstructed disappears.
//
// `expectName` is the validated filename stem. The record's name is taken
// from it, never from the frontmatter line: the frontmatter is content and a
// name read from there would be unvalidated where it rides into context and
// into path joins.
function parseRecord(text, expectName) {
    if (typeof text !== 'string') return { ok: false, reason: 'not text' };
    const lines = text.split(/\r?\n/);
    if (lines[0] !== '---') return { ok: false, reason: 'no frontmatter block' };

    const end = lines.indexOf('---', 1);
    if (end === -1) return { ok: false, reason: 'unterminated frontmatter block' };

    const record = { name: '', description: '', metadata: {}, body: '' };
    let declaredName = '';
    let inMetadata = false;

    for (let i = 1; i < end; i++) {
        const line = lines[i];
        if (!line.trim()) continue;

        // Any indent of two or more, and keys may carry dashes or dots. The
        // stricter forms silently dropped hand-written blocks.
        const nested = /^\s{2,}([A-Za-z][\w.-]*):[ \t]*(.*)$/.exec(line);
        if (inMetadata && nested) {
            record.metadata[nested[1]] = parseScalarOrList(nested[2]);
            continue;
        }

        const top = /^([A-Za-z][\w.-]*):[ \t]*(.*)$/.exec(line);
        if (!top) return { ok: false, reason: 'unparsable frontmatter line: ' + sanitize(line, 60) };
        inMetadata = top[1] === 'metadata';
        if (inMetadata) continue;
        if (top[1] === 'name') declaredName = unquote(top[2]);
        else if (top[1] === 'description') record.description = unquote(top[2]);
    }

    for (const field of LIST_FIELDS) {
        const value = record.metadata[field];
        if (typeof value === 'string') record.metadata[field] = value ? [value] : [];
    }

    record.body = lines.slice(end + 1).join('\n').replace(/^\n+/, '');
    if (!record.description) return { ok: false, reason: 'record has no description' };

    if (expectName !== undefined) {
        if (declaredName && declaredName !== expectName) {
            return { ok: false, reason: 'frontmatter name "' + sanitize(declaredName, 40) + '" does not match file "' + expectName + '"' };
        }
        record.name = expectName;
    } else {
        const check = validateName(declaredName);
        if (!check.ok) return { ok: false, reason: 'record name is unusable: ' + check.reason };
        record.name = declaredName;
    }
    return { ok: true, record };
}

// Serialize a record back to text. Unknown metadata keys are preserved so a
// field added by a later section is not dropped by an older writer.
function serializeRecord(record) {
    const md = record.metadata || {};
    const order = ['kind', 'machine', 'created', 'modified', 'applied', 'origin'];
    const known = order.filter(k => usable(md[k]));
    const extra = Object.keys(md).filter(k => !order.includes(k) && usable(md[k]));

    const out = ['---', 'name: ' + record.name, 'description: ' + record.description, 'metadata:'];
    for (const k of known.concat(extra)) {
        const v = md[k];
        out.push('  ' + k + ': ' + (Array.isArray(v) ? '[' + v.join(', ') + ']' : v));
    }
    out.push('---', '', (record.body || '').replace(/\s+$/, ''), '');
    return out.join('\n');
}

function usable(v) {
    return v !== undefined && v !== null && v !== '' && !(Array.isArray(v) && v.length === 0);
}

// Read and parse one record. Returns { ok, record } or { ok:false, reason }.
// The record carries `descriptionHash` and `bodyHash` for the index sidecar,
// and `partial` when only a frontmatter prefix was read, so a caller cannot
// write back a truncated body without noticing.
function readRecord(name, opts) {
    const check = validateName(name);
    if (!check.ok) return check;
    const file = recordPath(name);
    const wantPrefix = Boolean(opts && opts.frontmatterOnly);

    let read = readCapped(file, wantPrefix ? FRONTMATTER_READ_CAP : RECORD_READ_CAP);
    if (read === null) return { ok: false, reason: 'record not readable: ' + name };

    // A frontmatter block running past the prefix is a retry, never a drop.
    if (wantPrefix && read.truncated && read.text.indexOf('\n---', 3) === -1) {
        const full = readCapped(file, RECORD_READ_CAP);
        if (full !== null) read = full;
    }

    const parsed = parseRecord(read.text, name);
    if (!parsed.ok) return parsed;
    parsed.record.mtimeMs = read.mtimeMs;
    parsed.record.descriptionHash = hashOf(parsed.record.description);
    if (wantPrefix && read.truncated) {
        // The body is incomplete, so it is withheld rather than handed over
        // to be written back at its truncated length.
        parsed.record.partial = true;
        delete parsed.record.body;
    } else {
        parsed.record.bodyHash = hashOf(parsed.record.body);
    }
    return parsed;
}

// Every readable record in the store, parsed from a bounded prefix.
// Unreadable or malformed records are skipped and counted rather than
// throwing: a store with one bad file must still serve the other 59, and the
// count is what lets a caller say so out loud.
function listRecords() {
    let entries;
    try {
        entries = fs.readdirSync(storeRoot(), { withFileTypes: true });
    } catch {
        return { records: [], skipped: 0 };
    }
    const records = [];
    let skipped = 0;
    for (const entry of entries) {
        if (!entry.name.endsWith('.md')) continue;
        // A symlink is not a file under withFileTypes, but readRecord would
        // happily follow it. Counted as skipped either way so the two APIs
        // never disagree about whether a record exists.
        if (!entry.isFile()) { skipped++; continue; }
        const name = entry.name.slice(0, -3);
        if (!validateName(name).ok) { skipped++; continue; }
        const result = readRecord(name, { frontmatterOnly: true });
        if (!result.ok) { skipped++; continue; }
        records.push(result.record);
    }
    records.sort((a, b) => a.name.localeCompare(b.name));
    return { records, skipped };
}

// Create the store root if absent, private to the operator. The tier holds
// facts that can describe production configuration, so 0700/0600 rather than
// inheriting a 0022 umask.
function ensureStore() {
    try {
        fs.mkdirSync(storeRoot(), { recursive: true, mode: 0o700 });
        return { ok: true };
    } catch (err) {
        return { ok: false, reason: 'cannot create store: ' + sanitize(err.message, 120) };
    }
}

// Validate every authored field, then write atomically (tmp + rename). The
// tmp path carries the pid, matching kit-goal-lib.js: this tier is shared
// across concurrent sessions of every project, so two writers must never
// collide on one tmp path. Returns { ok, record } or { ok:false, reason };
// never throws.
function writeRecord(record, now) {
    if (!record || typeof record !== 'object') return { ok: false, reason: 'record is required' };
    const nameCheck = validateName(record.name);
    if (!nameCheck.ok) return nameCheck;
    if (record.partial) return { ok: false, reason: 'refusing to write a record read as a partial prefix' };

    const description = String(record.description == null ? '' : record.description).trim();
    if (!description) return { ok: false, reason: 'description is required: it generates the emitted index line' };
    if (description.length > DESCRIPTION_MAX) {
        return { ok: false, reason: 'description exceeds ' + DESCRIPTION_MAX + ' characters' };
    }
    const descCheck = validateFieldText(description, 'description');
    if (!descCheck.ok) return descCheck;

    const md = Object.assign({}, record.metadata);
    if (!KINDS.includes(md.kind)) {
        return { ok: false, reason: 'kind must be one of: ' + KINDS.join(', ') };
    }
    for (const [key, value] of Object.entries(md)) {
        if (!usable(value)) { delete md[key]; continue; }
        const values = Array.isArray(value) ? value : [value];
        for (const item of values) {
            const check = validateFieldText(String(item), 'metadata.' + key);
            if (!check.ok) return check;
            if (String(item).includes(',')) {
                return { ok: false, reason: 'metadata.' + key + ' must not contain a comma' };
            }
        }
        md[key] = Array.isArray(value) ? value.map(String) : String(value);
    }
    for (const day of (md.applied || [])) {
        if (!DATE_PATTERN.test(day)) return { ok: false, reason: 'applied entries must be YYYY-MM-DD' };
    }

    // Stamps are generated here so they cannot be forgotten by a caller; the
    // spec calls them unbackfillable, which makes "the caller sets them" the
    // wrong contract.
    const stamp = now instanceof Date ? now : new Date();
    if (!DATE_PATTERN.test(md.created || '')) md.created = stamp.toISOString().slice(0, 10);
    md.modified = stamp.toISOString();

    const ensured = ensureStore();
    if (!ensured.ok) return ensured;

    const finished = { name: record.name, description, metadata: md, body: record.body || '' };
    const file = recordPath(record.name);
    const tmp = file + '.tmp.' + process.pid;
    try {
        fs.writeFileSync(tmp, serializeRecord(finished), { encoding: 'utf8', mode: 0o600 });
        fs.renameSync(tmp, file);
        return { ok: true, record: finished };
    } catch (err) {
        try { fs.unlinkSync(tmp); } catch { /* nothing to clean up */ }
        return { ok: false, reason: 'write failed: ' + sanitize(err.message, 120) };
    }
}

module.exports = {
    KINDS,
    FRONTMATTER_READ_CAP,
    RECORD_READ_CAP,
    NAME_MAX,
    DESCRIPTION_MAX,
    storeRoot,
    recordPath,
    validateName,
    validateFieldText,
    sanitize,
    hashOf,
    parseRecord,
    serializeRecord,
    readRecord,
    listRecords,
    ensureStore,
    writeRecord,
};
